
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import "../public/template/css/sb-admin-2.min.css"
import "../public/template/css/fontawesome-free/css/all.min.css"
import "bootstrap/dist/css/bootstrap.min.css"
import "bootstrap-icons/font/bootstrap-icons.css";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "./context/userContext";

const nunito = Nunito({subsets: ['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="pt-br" className={nunito.className}>
        <head>
          <script async={true} src="/template/js/jquery.min.js"></script>
          <script async={true} src="/template/js/bootstrap.bundle.min.js"></script>
          <script async={true} src="/template/js/sb-admin-2.min.js"></script> 
        </head>
        <body>
          <div><Toaster></Toaster></div>
          {children}
        </body>
      </html>
    </UserProvider>
  );
}
